### ISSUE TITLE
Add web interface

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#31]
Currently Lexiguess is hosted on Render at this URL:

https://lexiguess.onrender.com/

Objective is to have it also playable there, directly from the web. Like you go to that URL and you can just start playing.

**Comment by dreeves** [comment]
I'm thinking xterm.js may be the nicest way to do this.

**Comment by dreeves** [comment]
Status: Jake tried pulling in code from before and setting up xterm.js and I deployed it to Render but I'm just seeing a blank green screen when I go to https://lexiguess.onrender.com/

**Comment by jakecoble** [comment]
What's left before we can close this one? Do we just need to get the xterm window to fill the screen?

**Comment by dreeves** [comment]
Let's close this and gissue things like full screen separately
