### ISSUE TITLE
Web client freezes when other web client connects

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#37]
## Replicata

1. Go to https://lexiguess.onrender.com and type some words
2. Open https://lexiguess.onrender.com in another computer or separate browser and type some words
3. Go back to the first browser and type more words

## Expectata

That I can still type words in the first browser.

## Resultata

I can't. :(

**Comment by dreeves** [comment]
Oops, I'm failing to replicate this! Maybe it just freezes after some amount of inactivity? This is on Chrome that it happened for me.

**Comment by jakecoble** [comment]
Haven't been able to reproduce this yet. I'll check from time to time.

**Comment by jakecoble** [comment]
Can't reproduce.
