### ISSUE TITLE
Add prompts for the website version

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#44]
## Replicata

1. Go to https://lexiguess.onrender.com
2. Start playing

## Expectata

That I have an interface roughly similar to Discord or IRC or whatever. Like if my nickname is bob then I'd see:

> Lexiguess!
> bob has joined the game.
> BOB: cat
> LEX: My word is between "cat" and "zebra"!
> BOB: dog
> LEX: My word is between "cat" and "dog"!

## Resultata

I enter things on a blank line and then it echos back what I entered with my username, like this:

![image](https://user-images.githubusercontent.com/9928/174503061-5990a8f9-b7bd-4701-a7ea-46d25b0adf25.png)

**Comment by jakecoble** [comment]
Is this still valid? There are prompts on the web interface.
