### ISSUE TITLE
Superfluous horizontal scrollbar

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#68]
## Replicata

1. Open the web version of the chat bot, https://lexiguess.onrender.com or currently https://lexiguess-pr-67.onrender.com/
2. Type lots of things
3. At some point stuff scrolls off the top of the screen

## Expectata

A vertical scrollbar appears.

## Resultata

A vertical scrollbar AND a horizontal scrollbar appears.

The horizontal scrollbar is slightly ugly.

This isn't actually important but maybe it's a trivial tweak?

## Cognata

* #46

_**Verbata**: css, aesthetics, scollbars, scroll bars, horizontal scroll bar,_

**Comment by jakecoble** [comment]
Invalidated by https://github.com/dreeves/lexiguess/pull/67
