### ISSUE TITLE
Make the dummy /bid command work in Slack + Discord + web

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#69]
## Desiderata

- [X] Make it work in Discord (#66)
- [x] Make it work in the web client
- [x] Make it work in Slack (note possible conflict with the Beeminder bot which also has a /bid command)

## Cognata

* #66 

_**Verbata**: slash commands, omnibot, cross-platform, common business logic,_

**Comment by dreeves** [comment]
New idea: make a separate `/omnitest` one to avoid confusion with conflicts with existing commands from other bots.

**Comment by jakecoble** [comment]
Completed by #91
