### ISSUE TITLE
Put the cursor in the text box on page load for the web interface

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#76]
## Replicata

1. Go to lexiguess.onrender.com
2. Type a word

## Expectata

That the cursor is there in the text box and it works fine.

## Resultata

Nothing happens when I type. I have to click in that area at the very bottom of the screen first, which might be nonobvious.

_**Verbata**: web interface, auto-focus,_

**Comment by dreeves** [comment]
This regressed, I believe with #43 when we added the popup to pick a username.

**Comment by jakecoble** [comment]
zapped by #101

**Comment by jakecoble** [comment]
Didn't mean to close!
