### ISSUE TITLE
Make dummy /bid command slightly less dumb

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#89]
The /bid command needs to parse and understand username/@-mentions. This gissue is to make the dummy version of /bid be like:

alice: `/bid let us have an auction with @bob and @carol`
bot: `roger that "let us have an auction with @bob and @carol" sent by @alice. here is a list of all users who have sent the /bid command or been @-mentioned in a /bid command: {@alice, @bob, @carol}`

(no database -- it just keeps state similarly to how the lexiguess game does)

**Comment by jakecoble** [comment]
Added in #93
