### ISSUE TITLE
Make slash commands not be echoed in the web client

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#90]
For some slash commands (like the /bid command for placing sealed bids) it's important that the slash command the user typed NOT be echoed to the chat for all to see.

The web client isn't a high priority right now but it's probably not hard to have the web client suppress the echoing of slash commands.

## Desiderata

- [x] Confirm if that's easy
- [x] Do it

**Comment by jakecoble** [comment]
Fixed by #92
